name: nextjs-task
services:
  postgres:
    image: postgres:15
    container_name: nextjs-task-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - nextjs-task-db-data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - nextjs-task-network

volumes:
  nextjs-task-db-data:

networks:
  nextjs-task-network:
    name: nextjs-task-network
